/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 nine.gltf --transform
Author: Rude Randal (https://sketchfab.com/Rude_Randal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chibi-three-tailed-kitsune-model-b736a0775a8643c8a81671cdf324e1c2
Title: Chibi Three Tailed Kitsune Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./nine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_Character_Texture_0.geometry} material={materials.Character_Texture} position={[0, 0.915, 0.192]} rotation={[-Math.PI / 2, 0, 0]} scale={0.363} />
      <mesh geometry={nodes.Plane_Outline_0.geometry} material={materials.Outline} position={[0, 0.915, 0.192]} rotation={[-Math.PI / 2, 0, 0]} scale={0.363} />
      <mesh geometry={nodes.Plane002_Material001_0.geometry} material={materials['Material.001']} position={[0, 0.004, -0.308]} rotation={[-Math.PI / 2, 0, 0]} scale={1.325} />
    </group>
  )
}

useGLTF.preload('./nine-transformed.glb')
